#include "HansaAutomationModule.h"
#include "Misc/AutomationTest.h"
#include "Misc/CommandLine.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Misc/Parse.h"
#include "Protocol/HansaAutomationProtocol.h"
#include "Screenshot/HansaNativeScreenshotService.h"
#include "SemanticUI/HansaSemanticUiRegistry.h"
#include "Session/HansaAutomationSessionService.h"
#include "Synchronization/HansaAutomationWaitService.h"

#if WITH_DEV_AUTOMATION_TESTS && WITH_HANSA_AUTOMATION

namespace Hansa::Tests::Automation
{
	using namespace Hansa::Automation;

	constexpr TCHAR TestToken[] = TEXT("hansa-test-token-0001");

	FHansaAutomationRequestContext MakeContext(
		const FString& CorrelationId,
		const int64 EnqueuedAt = 1000,
		const int64 Timeout = 1000)
	{
		return FHansaAutomationRequestContext { CorrelationId, EnqueuedAt, Timeout };
	}

	FHansaAutomationOpenSessionRequest MakeOpenRequest(
		const FString& ControllerId = TEXT("controller.primary"),
		const EHansaAutomationPermissionLevel Permission = EHansaAutomationPermissionLevel::ReadOnly)
	{
		FHansaAutomationOpenSessionRequest Request;
		Request.ControllerId = ControllerId;
		Request.AuthenticationToken = TestToken;
		Request.RequestedPermission = Permission;
		Request.RequiredCapabilities = {
			EHansaAutomationCapability::Session,
			EHansaAutomationCapability::CapabilityDiscovery,
			EHansaAutomationCapability::Health
		};
		return Request;
	}

	FHansaAutomationSessionService MakeService(
		const int64& Now,
		const EHansaAutomationPermissionLevel MaximumPermission = EHansaAutomationPermissionLevel::ReadOnly,
		const bool bEnabled = true,
		const bool bSupportControlledCommands = false)
	{
		FHansaAutomationSessionSettings Settings = FHansaAutomationSessionSettings::CreateDefault(
			bEnabled,
			MaximumPermission,
			bEnabled ? FString(TestToken) : FString());
		(void)bSupportControlledCommands;
		return FHansaAutomationSessionService(MoveTemp(Settings), [&Now] { return Now; });
	}

	bool LoadProjectText(FAutomationTestBase& Test, const FString& RelativePath, FString& OutText)
	{
		const FString Path = FPaths::Combine(FPaths::ProjectDir(), RelativePath);
		return Test.TestTrue(
			FString::Printf(TEXT("Read Shipping-boundary source: %s"), *RelativePath),
			FFileHelper::LoadFileToString(OutText, *Path));
	}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationDisabledByDefaultTest,
	"Hansa.Architecture.Automation.DisabledByDefault",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationDisabledByDefaultTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 1000;
	FHansaAutomationSessionService Service = MakeService(Now, EHansaAutomationPermissionLevel::ReadOnly, false);
	const FHansaAutomationCapabilityResult Capabilities = Service.DiscoverCapabilities(MakeContext(TEXT("disabled.capabilities")));
	TestFalse(TEXT("Disabled service exposes no capability manifest"), Capabilities.IsSuccess());
	TestTrue(TEXT("Disabled service returns structured Disabled error"),
		Capabilities.GetError().Code == EHansaAutomationErrorCode::Disabled);
	TestFalse(TEXT("Disabled service has no active session"), Service.HasActiveSession());

	if (!FParse::Param(FCommandLine::Get(), TEXT("HansaAutomation")))
	{
		TestFalse(TEXT("Module session boundary is disabled on the ordinary test command line"),
			FHansaAutomationModule::Get().IsSessionBoundaryEnabled());
	}
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationSessionLifecycleTest,
	"Hansa.Architecture.Automation.SessionLifecycle",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationSessionLifecycleTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 1000;
	FHansaAutomationSessionService Service = MakeService(Now);

	const FHansaAutomationCapabilityResult Capabilities = Service.DiscoverCapabilities(MakeContext(TEXT("lifecycle.capabilities")));
	TestTrue(TEXT("Enabled service publishes capabilities"), Capabilities.IsSuccess());
	TestEqual(TEXT("S03-P04 manifest exposes session, production and semantic evidence capabilities"), Capabilities.GetPayload().Capabilities.Num(), 9);

	const FHansaAutomationOpenSessionRequest OpenRequest = MakeOpenRequest();
	const FHansaAutomationOpenSessionResult Open = Service.OpenSession(OpenRequest, MakeContext(TEXT("lifecycle.open")));
	if (!TestTrue(TEXT("Compatible authenticated session opens"), Open.IsSuccess()))
	{
		return false;
	}
	const FString SessionId = Open.GetPayload().SessionId;
	TestFalse(TEXT("Session ID is generated by the process"), SessionId.IsEmpty());
	TestEqual(TEXT("Granted permission is explicit"),
		static_cast<uint8>(Open.GetPayload().Permission),
		static_cast<uint8>(EHansaAutomationPermissionLevel::ReadOnly));

	const FHansaAutomationOpenSessionResult Duplicate = Service.OpenSession(OpenRequest, MakeContext(TEXT("lifecycle.duplicate")));
	TestTrue(TEXT("Same controller cannot silently replace an active session"),
		Duplicate.GetError().Code == EHansaAutomationErrorCode::SessionAlreadyOpen);
	const FHansaAutomationOpenSessionResult Conflict = Service.OpenSession(
		MakeOpenRequest(TEXT("controller.second")),
		MakeContext(TEXT("lifecycle.conflict")));
	TestTrue(TEXT("Second controller is rejected"),
		Conflict.GetError().Code == EHansaAutomationErrorCode::ControllerConflict);

	TestTrue(TEXT("Session identity can be queried"),
		Service.GetSession(SessionId, OpenRequest.ControllerId, MakeContext(TEXT("lifecycle.get"))).IsSuccess());
	TestTrue(TEXT("Granted health operation authorizes"),
		Service.AuthorizeOperation(
			SessionId,
			OpenRequest.ControllerId,
			EHansaAutomationOperation::HealthGet,
			MakeContext(TEXT("lifecycle.health"))).IsSuccess());
	TestTrue(TEXT("Matching controller closes the session"),
		Service.CloseSession(SessionId, OpenRequest.ControllerId, MakeContext(TEXT("lifecycle.close"))).IsSuccess());
	const FHansaAutomationSessionResult ClosedQuery = Service.GetSession(
		SessionId,
		OpenRequest.ControllerId,
		MakeContext(TEXT("lifecycle.closed")));
	TestTrue(TEXT("Closed session is unavailable"),
		ClosedQuery.GetError().Code == EHansaAutomationErrorCode::NoActiveSession);
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationProtocolAndAuthenticationTest,
	"Hansa.Architecture.Automation.ProtocolAndAuthentication",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationProtocolAndAuthenticationTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 1000;
	FHansaAutomationSessionService Service = MakeService(Now);

	FHansaAutomationOpenSessionRequest Incompatible = MakeOpenRequest();
	Incompatible.ProtocolVersion = FHansaAutomationProtocolVersion { 2, 0 };
	const FHansaAutomationOpenSessionResult VersionResult = Service.OpenSession(
		Incompatible,
		MakeContext(TEXT("protocol.incompatible")));
	TestTrue(TEXT("Incompatible protocol fails closed"),
		VersionResult.GetError().Code == EHansaAutomationErrorCode::IncompatibleProtocol);
	TestEqual(TEXT("Protocol error retains correlation identity"),
		VersionResult.GetError().CorrelationId,
		FString(TEXT("protocol.incompatible")));

	FHansaAutomationOpenSessionRequest WrongToken = MakeOpenRequest();
	WrongToken.AuthenticationToken = TEXT("incorrect-token-0000");
	const FHansaAutomationOpenSessionResult AuthenticationResult = Service.OpenSession(
		WrongToken,
		MakeContext(TEXT("protocol.authentication")));
	TestTrue(TEXT("Wrong token is rejected"),
		AuthenticationResult.GetError().Code == EHansaAutomationErrorCode::AuthenticationFailed);
	TestFalse(TEXT("Authentication errors never echo a supplied token"),
		AuthenticationResult.GetError().Message.Contains(WrongToken.AuthenticationToken));
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationCapabilitiesAndPermissionsTest,
	"Hansa.Architecture.Automation.CapabilitiesAndPermissions",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationCapabilitiesAndPermissionsTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 1000;
	FHansaAutomationSessionService Service = MakeService(Now);

	FHansaAutomationOpenSessionRequest QueryCapability = MakeOpenRequest();
	QueryCapability.RequiredCapabilities.Add(EHansaAutomationCapability::GameplayQueries);
	const FHansaAutomationOpenSessionResult QueryResult = Service.OpenSession(
		QueryCapability,
		MakeContext(TEXT("capability.query")));
	TestTrue(TEXT("Real gameplay query adapter can be negotiated read-only"), QueryResult.IsSuccess());
	if (QueryResult)
	{
		Service.CloseSession(QueryResult.GetPayload().SessionId, QueryCapability.ControllerId, MakeContext(TEXT("capability.close")));
	}

	const FHansaAutomationOpenSessionResult PermissionResult = Service.OpenSession(
		MakeOpenRequest(TEXT("controller.primary"), EHansaAutomationPermissionLevel::ControlledActions),
		MakeContext(TEXT("permission.ceiling")));
	TestTrue(TEXT("Client cannot exceed the startup permission ceiling"),
		PermissionResult.GetError().Code == EHansaAutomationErrorCode::PermissionDenied);
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationRejectedCommandsTest,
	"Hansa.Architecture.Automation.RejectedCommands",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationRejectedCommandsTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 1000;
	FHansaAutomationSessionService Service = MakeService(
		Now,
		EHansaAutomationPermissionLevel::ControlledActions,
		true,
		true);

	const FHansaAutomationOpenSessionRequest ReadOnlyRequest = MakeOpenRequest();
	const FHansaAutomationOpenSessionResult ReadOnlyOpen = Service.OpenSession(
		ReadOnlyRequest,
		MakeContext(TEXT("command.open-read")));
	if (!TestTrue(TEXT("Read-only session opens"), ReadOnlyOpen.IsSuccess()))
	{
		return false;
	}
	const FHansaAutomationOperationResult RejectedCommand = Service.AuthorizeOperation(
		ReadOnlyOpen.GetPayload().SessionId,
		ReadOnlyRequest.ControllerId,
		EHansaAutomationOperation::ControlledCommand,
		MakeContext(TEXT("command.rejected")));
	TestTrue(TEXT("Command without an explicitly granted capability is rejected"),
		RejectedCommand.GetError().Code == EHansaAutomationErrorCode::MissingCapability);
	Service.CloseSession(
		ReadOnlyOpen.GetPayload().SessionId,
		ReadOnlyRequest.ControllerId,
		MakeContext(TEXT("command.close-read")));

	FHansaAutomationOpenSessionRequest ControlledRequest = MakeOpenRequest(
		TEXT("controller.controlled"),
		EHansaAutomationPermissionLevel::ControlledActions);
	ControlledRequest.RequiredCapabilities.Add(EHansaAutomationCapability::ControlledCommands);
	const FHansaAutomationOpenSessionResult ControlledOpen = Service.OpenSession(
		ControlledRequest,
		MakeContext(TEXT("command.open-controlled")));
	if (!TestTrue(TEXT("Startup-approved controlled capability can be negotiated"), ControlledOpen.IsSuccess()))
	{
		return false;
	}
	const FHansaAutomationOperationResult UnknownOperation = Service.AuthorizeOperation(
		ControlledOpen.GetPayload().SessionId,
		ControlledRequest.ControllerId,
		static_cast<EHansaAutomationOperation>(255),
		MakeContext(TEXT("command.unknown")));
	TestTrue(TEXT("Unknown operation cannot become an arbitrary command surface"),
		UnknownOperation.GetError().Code == EHansaAutomationErrorCode::OperationUnsupported);
	TestTrue(TEXT("Explicitly allowlisted controlled operation authorizes"),
		Service.AuthorizeOperation(
			ControlledOpen.GetPayload().SessionId,
			ControlledRequest.ControllerId,
			EHansaAutomationOperation::ControlledCommand,
			MakeContext(TEXT("command.allowed"))).IsSuccess());
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationTimeoutAndCorrelationTest,
	"Hansa.Architecture.Automation.TimeoutAndCorrelation",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationTimeoutAndCorrelationTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	using namespace Hansa::Tests::Automation;
	const int64 Now = 2000;
	FHansaAutomationSessionService Service = MakeService(Now);

	const FHansaAutomationCapabilityResult TimedOut = Service.DiscoverCapabilities(
		MakeContext(TEXT("timeout.expired"), 1000, 1000));
	TestTrue(TEXT("Expired request returns TimedOut"),
		TimedOut.GetError().Code == EHansaAutomationErrorCode::TimedOut);
	TestTrue(TEXT("Timeout advertises retryability"), TimedOut.GetError().bRetryable);
	TestEqual(TEXT("Timeout retains correlation identity"),
		TimedOut.GetError().CorrelationId,
		FString(TEXT("timeout.expired")));

	const FHansaAutomationCapabilityResult InvalidCorrelation = Service.DiscoverCapabilities(
		MakeContext(TEXT("not allowed / path"), 2000, 1000));
	TestTrue(TEXT("Unsafe correlation identity is rejected"),
		InvalidCorrelation.GetError().Code == EHansaAutomationErrorCode::InvalidCorrelationId);
	const FHansaAutomationCapabilityResult InvalidTimeout = Service.DiscoverCapabilities(
		MakeContext(TEXT("timeout.unbounded"), 2000, 30001));
	TestTrue(TEXT("Unbounded timeout is rejected"),
		InvalidTimeout.GetError().Code == EHansaAutomationErrorCode::InvalidTimeout);
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaAutomationShippingUnavailableTest,
	"Hansa.Architecture.Automation.ShippingUnavailable",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaAutomationShippingUnavailableTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Tests::Automation;
	FString TargetRules;
	FString AutomationRules;
	FString ModuleSource;
	FString RuntimeRules;
	if (!LoadProjectText(*this, TEXT("Source/Hansa.Target.cs"), TargetRules) ||
		!LoadProjectText(*this, TEXT("Source/HansaAutomation/HansaAutomation.Build.cs"), AutomationRules) ||
		!LoadProjectText(*this, TEXT("Source/HansaAutomation/Private/HansaAutomationModule.cpp"), ModuleSource) ||
		!LoadProjectText(*this, TEXT("Source/Hansa/Hansa.Build.cs"), RuntimeRules))
	{
		return false;
	}
	TestTrue(TEXT("Game target excludes automation when configuration is Shipping"),
		TargetRules.Contains(TEXT("Configuration != UnrealTargetConfiguration.Shipping")) &&
		TargetRules.Contains(TEXT("ExtraModuleNames.Add(\"HansaAutomation\")")));
	TestTrue(TEXT("Automation rules refuse Shipping compilation"),
		AutomationRules.Contains(TEXT("Target.Configuration == UnrealTargetConfiguration.Shipping")) &&
		AutomationRules.Contains(TEXT("throw new BuildException")));
	TestTrue(TEXT("Automation module has a compile-time Shipping tripwire"),
		ModuleSource.Contains(TEXT("#if UE_BUILD_SHIPPING")) &&
		ModuleSource.Contains(TEXT("#error HansaAutomation must never be compiled")));
	TestTrue(TEXT("Short-lived token comes from the process environment"),
		ModuleSource.Contains(TEXT("HANSA_AUTOMATION_TOKEN")) &&
		!ModuleSource.Contains(TEXT("HansaAutomationToken=")));
	TestTrue(TEXT("Runtime automation seam compiles to zero in Shipping"),
		RuntimeRules.Contains(TEXT("Target.Configuration != UnrealTargetConfiguration.Shipping")));
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaSemanticUiRegistryTest,
	"Hansa.Architecture.Automation.SemanticRegistry",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaSemanticUiRegistryTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	FHansaSemanticUiRegistry Registry;
	FHansaSemanticNode Screen;
	Screen.Id = TEXT("AutomationProof.Screen");
	Screen.Role = EHansaSemanticRole::Screen;
	Screen.Label = TEXT("Automation Proof");
	TestTrue(TEXT("Stable root semantic node registers"), Registry.RegisterNode(Screen));

	bool bActivated = false;
	FHansaSemanticNode Button;
	Button.Id = TEXT("AutomationProof.Activate");
	Button.ParentId = Screen.Id;
	Button.Role = EHansaSemanticRole::Button;
	Button.Label = TEXT("Activate");
	Button.Actions = { EHansaSemanticAction::Activate, EHansaSemanticAction::Focus };
	TestTrue(TEXT("Child node registers independently of widget class"), Registry.RegisterNode(
		Button,
		FHansaSemanticActionHandlers {
			[&bActivated] { bActivated = true; return true; },
			[] { return true; }
		}));
	const FHansaSemanticNode* Root = Registry.FindNode(Screen.Id);
	TestTrue(TEXT("Parent exposes stable child relationship"), Root != nullptr && Root->ChildIds.Contains(Button.Id));
	const FHansaSemanticNode* RegisteredButton = Registry.FindNode(Button.Id);
	TestTrue(TEXT("Role, label and action contract are observable"),
		RegisteredButton != nullptr && RegisteredButton->Role == EHansaSemanticRole::Button &&
		RegisteredButton->Label == TEXT("Activate") && RegisteredButton->Actions.Num() == 2);

	FHansaSemanticState State;
	State.bSelected = true;
	TestTrue(TEXT("State and bounds update through semantic record"),
		Registry.UpdateNode(Button.Id, State, { 10, 20, 200, 48 }));
	const uint64 RevisionBeforeAction = Registry.GetRevision();
	const FHansaSemanticActionResult Action = Registry.Invoke(Button.Id, EHansaSemanticAction::Activate);
	TestTrue(TEXT("Advertised activation invokes bounded handler"), Action.IsSuccess() && bActivated);
	TestTrue(TEXT("Semantic revision advances monotonically"), Registry.GetRevision() > RevisionBeforeAction);
	TestTrue(TEXT("Invalid and missing IDs fail closed"),
		!IsValidSemanticId(TEXT("unsafe/path")) &&
		!Registry.Invoke(TEXT("AutomationProof.Missing"), EHansaSemanticAction::Activate).IsSuccess());
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaObservableWaitTest,
	"Hansa.Architecture.Automation.ObservableWait",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaObservableWaitTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	FHansaSemanticUiRegistry Registry;
	FHansaSemanticNode Node;
	Node.Id = TEXT("AutomationProof.Status");
	Node.Role = EHansaSemanticRole::Status;
	Node.Label = TEXT("Ready");
	Registry.RegisterNode(Node);
	FHansaAutomationWaitService Waits(Registry);

	bool bCompleted = false;
	FHansaSemanticWaitResult Completion;
	TestTrue(TEXT("Unsatisfied observable predicate registers without blocking"), Waits.BeginWait(
		TEXT("wait-selected"),
		{ Node.Id, EHansaSemanticProperty::Selected, true },
		2000,
		[&bCompleted, &Completion](const FHansaSemanticWaitResult& Result)
		{
			bCompleted = true;
			Completion = Result;
		}));
	TestEqual(TEXT("Wait remains pending before observable state change"), Waits.NumPending(), 1);
	Waits.Tick(1000);
	TestFalse(TEXT("Ticker observation does not complete a false predicate"), bCompleted);
	FHansaSemanticState Selected;
	Selected.bSelected = true;
	Registry.UpdateNode(Node.Id, Selected, { 0, 0, 100, 20 });
	Waits.Tick(1001);
	TestTrue(TEXT("Registry state change satisfies wait on next observation"), bCompleted && Completion.bMatched && !Completion.bTimedOut);

	bool bTimedOut = false;
	Waits.BeginWait(
		TEXT("wait-error"),
		{ Node.Id, EHansaSemanticProperty::Error, true },
		1010,
		[&bTimedOut](const FHansaSemanticWaitResult& Result) { bTimedOut = Result.bTimedOut; });
	Waits.Tick(1010);
	TestTrue(TEXT("Bounded monotonic deadline completes unmatched wait structurally"), bTimedOut);
	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FHansaNativeScreenshotEvidenceTest,
	"Hansa.Architecture.Automation.NativeScreenshotEvidence",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FHansaNativeScreenshotEvidenceTest::RunTest(const FString& Parameters)
{
	using namespace Hansa::Automation;
	FHansaNativeScreenshotService Service;
	auto CaptureSolidPixels = [](const FIntPoint& Size, TArray<FColor>& Pixels)
	{
		Pixels.Init(FColor(21, 42, 53, 255), Size.X * Size.Y);
		return true;
	};
	auto VerifyNativePng = [this, &Service, &CaptureSolidPixels](const FIntPoint Size, const TCHAR* BundleId)
	{
		FHansaScreenshotContext Context;
		Context.BundleId = BundleId;
		Context.CaptureMethod = TEXT("AutomationTest.SyntheticNativeBuffer");
		Context.SemanticSnapshotJson = TEXT("{\"schemaVersion\":1,\"revision\":1,\"nodes\":[]}");
		Context.UiRevision = 1;
		const FHansaScreenshotResult Result = Service.Capture(Size, Context, CaptureSolidPixels);
		if (!TestTrue(FString::Printf(TEXT("Native %dx%d evidence writes"), Size.X, Size.Y), Result.IsSuccess()))
		{
			return;
		}
		TArray<uint8> Png;
		TestTrue(TEXT("PNG evidence can be read"), FFileHelper::LoadFileToArray(Png, *Result.ScreenshotPath));
		if (Png.Num() >= 24)
		{
			const int32 EncodedWidth = (Png[16] << 24) | (Png[17] << 16) | (Png[18] << 8) | Png[19];
			const int32 EncodedHeight = (Png[20] << 24) | (Png[21] << 16) | (Png[22] << 8) | Png[23];
			TestEqual(TEXT("PNG width equals requested native width"), EncodedWidth, Size.X);
			TestEqual(TEXT("PNG height equals requested native height"), EncodedHeight, Size.Y);
		}
		FString Metadata;
		TestTrue(TEXT("Capture metadata can be read"), FFileHelper::LoadFileToString(Metadata, *Result.MetadataPath));
		TestTrue(TEXT("Metadata proves no post-capture resizing"), Metadata.Contains(TEXT("\"postCaptureResized\":false")));
	};

	VerifyNativePng(FIntPoint(1280, 720), TEXT("unreal-contract-720"));
	VerifyNativePng(FIntPoint(1920, 1080), TEXT("unreal-contract-1080"));
	FHansaScreenshotContext InvalidContext;
	InvalidContext.BundleId = TEXT("invalid-size");
	TestTrue(TEXT("Unsupported capture size fails before native capture"),
		Service.Capture(FIntPoint(1366, 768), InvalidContext, CaptureSolidPixels).Error == EHansaScreenshotError::InvalidSize);
	return !HasAnyErrors();
}

#endif
