#include "UI/HansaHudSemanticIds.h"

namespace Hansa::UI
{
	TConstArrayView<FHansaHudSemanticId> GetMvpHudSemanticIds()
	{
		static constexpr FHansaHudSemanticId Contract[] = {
			{ TEXT("Root HUD shell"), TEXT("HUD.Root"), TEXT(""), false },
			{ TEXT("Top status bar"), TEXT("HUD.TopStatus"), TEXT("HUD.Root"), false },
			{ TEXT("House crest"), TEXT("HUD.TopStatus.HouseCrest"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Money summary"), TEXT("HUD.TopStatus.Money"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Money trend"), TEXT("HUD.TopStatus.MoneyTrend"), TEXT("HUD.TopStatus.Money"), false },
			{ TEXT("Population summary"), TEXT("HUD.TopStatus.Population"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Workforce summary"), TEXT("HUD.TopStatus.Workforce"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Selected-city breadcrumb"), TEXT("HUD.TopStatus.CityBreadcrumb"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Season and date"), TEXT("HUD.TopStatus.DateSeason"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Time and speed group"), TEXT("HUD.TopStatus.Speed"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Pause control"), TEXT("HUD.TopStatus.Speed.Pause"), TEXT("HUD.TopStatus.Speed"), false },
			{ TEXT("Normal-speed control"), TEXT("HUD.TopStatus.Speed.Normal"), TEXT("HUD.TopStatus.Speed"), false },
			{ TEXT("Fast-speed control"), TEXT("HUD.TopStatus.Speed.Fast"), TEXT("HUD.TopStatus.Speed"), false },
			{ TEXT("Fastest-speed control"), TEXT("HUD.TopStatus.Speed.Fastest"), TEXT("HUD.TopStatus.Speed"), false },
			{ TEXT("Research summary"), TEXT("HUD.TopStatus.Research"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Connection state"), TEXT("HUD.TopStatus.Connection"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Save and load control"), TEXT("HUD.TopStatus.SaveLoad"), TEXT("HUD.TopStatus"), false },
			{ TEXT("Save and load host"), TEXT("HUD.SaveLoadHost"), TEXT("HUD.Root"), false },
			{ TEXT("Save and load screen"), TEXT("SaveLoad.Root"), TEXT("HUD.SaveLoadHost"), false },
			{ TEXT("Save slot instance"), TEXT("SaveLoad.Slot"), TEXT("SaveLoad.Root"), true },
			{ TEXT("Save action"), TEXT("SaveLoad.Action.Save"), TEXT("SaveLoad.Root"), false },
			{ TEXT("Load action"), TEXT("SaveLoad.Action.Load"), TEXT("SaveLoad.Root"), false },
			{ TEXT("Save load confirmation"), TEXT("SaveLoad.Confirmation"), TEXT("SaveLoad.Root"), false },
			{ TEXT("Confirmation accept"), TEXT("SaveLoad.Confirmation.Confirm"), TEXT("SaveLoad.Confirmation"), false },
			{ TEXT("Confirmation cancel"), TEXT("SaveLoad.Confirmation.Cancel"), TEXT("SaveLoad.Confirmation"), false },
			{ TEXT("Save load status"), TEXT("SaveLoad.Status"), TEXT("SaveLoad.Root"), false },
			{ TEXT("Objectives and alert stack"), TEXT("HUD.AlertStack"), TEXT("HUD.Root"), false },
			{ TEXT("Alert stack collapse control"), TEXT("HUD.AlertStack.Toggle"), TEXT("HUD.AlertStack"), false },
			{ TEXT("Alert group instance"), TEXT("HUD.AlertStack.Group"), TEXT("HUD.AlertStack"), true },
			{ TEXT("Alert instance"), TEXT("HUD.AlertStack.Alert"), TEXT("HUD.AlertStack"), true },
			{ TEXT("Alert action instance"), TEXT("HUD.AlertStack.Alert.Action"), TEXT("HUD.AlertStack.Alert"), true },
			{ TEXT("Pinned tracker list"), TEXT("HUD.PinnedTrackers"), TEXT("HUD.AlertStack"), false },
			{ TEXT("Pinned tracker instance"), TEXT("HUD.PinnedTrackers.Tracker"), TEXT("HUD.PinnedTrackers"), true },
			{ TEXT("Bottom build and selection area"), TEXT("HUD.BottomArea"), TEXT("HUD.Root"), false },
			{ TEXT("Inspector host"), TEXT("HUD.InspectorHost"), TEXT("HUD.Root"), false },
			{ TEXT("Notification layer"), TEXT("HUD.NotificationLayer"), TEXT("HUD.Root"), false },
			{ TEXT("Notification instance"), TEXT("HUD.NotificationLayer.Notification"), TEXT("HUD.NotificationLayer"), true },
			{ TEXT("Tooltip layer"), TEXT("HUD.TooltipLayer"), TEXT("HUD.Root"), false },
			{ TEXT("Controller focus layer"), TEXT("HUD.FocusLayer"), TEXT("HUD.Root"), false },
			{ TEXT("Build menu"), TEXT("BuildMenu.Root"), TEXT("HUD.BottomArea"), false },
			{ TEXT("Build category list"), TEXT("BuildMenu.Categories"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Build category instance"), TEXT("BuildMenu.Category"), TEXT("BuildMenu.Categories"), true },
			{ TEXT("Building card list"), TEXT("BuildMenu.Cards"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Building card instance"), TEXT("BuildMenu.Card"), TEXT("BuildMenu.Cards"), true },
			{ TEXT("Selected building details"), TEXT("BuildMenu.Selection"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Favorite card action"), TEXT("BuildMenu.CardAction.Favorite"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Compare card action"), TEXT("BuildMenu.CardAction.Compare"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Recently used list"), TEXT("BuildMenu.Recent"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Favorites list"), TEXT("BuildMenu.Favorites"), TEXT("BuildMenu.Root"), false },
			{ TEXT("Placement surface"), TEXT("Placement.Root"), TEXT("HUD.Root"), false },
			{ TEXT("Placement preview"), TEXT("Placement.Preview"), TEXT("Placement.Root"), false },
			{ TEXT("Placement footprint"), TEXT("Placement.Footprint"), TEXT("Placement.Preview"), false },
			{ TEXT("Placement validation"), TEXT("Placement.Validation"), TEXT("Placement.Root"), false },
			{ TEXT("Placement validation cause"), TEXT("Placement.Validation.Cause"), TEXT("Placement.Validation"), false },
			{ TEXT("Placement validation remedy"), TEXT("Placement.Validation.Remedy"), TEXT("Placement.Validation"), false },
			{ TEXT("Placement overlay toggle instance"), TEXT("Placement.Overlay"), TEXT("Placement.Root"), true },
			{ TEXT("Placement target instance"), TEXT("Placement.Target"), TEXT("Placement.Root"), true },
			{ TEXT("Rotate action"), TEXT("Placement.Action.Rotate"), TEXT("Placement.Root"), false },
			{ TEXT("Repeat action"), TEXT("Placement.Action.Repeat"), TEXT("Placement.Root"), false },
			{ TEXT("Confirm action"), TEXT("Placement.Action.Confirm"), TEXT("Placement.Root"), false },
			{ TEXT("Cancel action"), TEXT("Placement.Action.Cancel"), TEXT("Placement.Root"), false },
			{ TEXT("Context inspector"), TEXT("Inspector.Root"), TEXT("HUD.InspectorHost"), false },
			{ TEXT("Inspector identity and state"), TEXT("Inspector.Identity"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector primary result"), TEXT("Inspector.Result"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector inputs, outputs or needs"), TEXT("Inspector.Flows"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector flow or need instance"), TEXT("Inspector.Flows.Item"), TEXT("Inspector.Flows"), true },
			{ TEXT("Inspector current problem"), TEXT("Inspector.Problem"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector causal explanation"), TEXT("Inspector.Problem.Cause"), TEXT("Inspector.Problem"), false },
			{ TEXT("Inspector action list"), TEXT("Inspector.Actions"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector action instance"), TEXT("Inspector.Action"), TEXT("Inspector.Actions"), true },
			{ TEXT("Inspector history"), TEXT("Inspector.History"), TEXT("Inspector.Root"), false },
			{ TEXT("Inspector history instance"), TEXT("Inspector.History.Item"), TEXT("Inspector.History"), true },
			{ TEXT("Inspector causal tooltip"), TEXT("Inspector.Tooltip.OpenCause"), TEXT("HUD.TooltipLayer"), false },
			{ TEXT("Inspector close control"), TEXT("Inspector.Close"), TEXT("Inspector.Root"), false }
		};
		return MakeArrayView(Contract);
	}
}
