case EHansaGameplayCommandType::RequestPresenceUpgrade:
{
 const auto& P=Command.GetRequestPresenceUpgrade();
 auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});
 const auto* Registry=Definitions.GetEconomicRegistry(); const auto* Policy=Registry?Registry->FindCityTradePolicyForCity(P.CityId.ToString()):nullptr;
 const auto* Target=Registry?Registry->FindPresenceStage(P.TargetStageId):nullptr;
 if(!Presence||!Policy||!Target||Presence->Status!=EHansaForeignPresenceStatus::Active||Presence->Upgrade.Status!=EHansaPresenceUpgradeStatus::None||
  !Registry->IsValidPresenceTransition(P.CityId.ToString(),Presence->CurrentStageId,P.TargetStageId)) return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeUnavailable,CommandIndex);
 const auto& C=Presence->Contributions;
 if(C.LawfulTradeVolumeMilliUnits<Target->RequiredLawfulTradeVolumeMilliUnits||C.CompletedDeliveryCount<Target->RequiredCompletedDeliveries||
  (C.InvestedPfennig>MAX_int64-Target->UpgradeCostPfennig?MAX_int64:C.InvestedPfennig+Target->UpgradeCostPfennig)<Target->RequiredInvestedPfennig||C.TransactionValuePfennig<Target->RequiredTransactionValuePfennig||
  C.FulfilledShortageMilliUnits<Target->RequiredFulfilledShortageMilliUnits||C.ReliableOperatingTicks<Target->RequiredReliableOperatingTicks||
  C.SolventOperatingTicks<Target->RequiredSolventOperatingTicks) return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeRequirementsUnmet,CommandIndex);
 Presence->Upgrade.Status=EHansaPresenceUpgradeStatus::Requested;Presence->Upgrade.TargetStageId=P.TargetStageId;Presence->Upgrade.RequestedTick=TickBefore;
 Presence->History.Add({EHansaPresenceHistoryKind::UpgradeRequested,TickBefore,Event.GlobalSequence,P.TargetStageId,0,0});
 Event.Type=EHansaDomainEventType::PresenceUpgradeRequested;Event.CityId=P.CityId;Event.Value=Target->UpgradeCostPfennig;break;
}
case EHansaGameplayCommandType::FundPresenceUpgrade:
{
 const auto& P=Command.GetFundPresenceUpgrade();
 auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});
 const auto* Registry=Definitions.GetEconomicRegistry();const auto* Target=Registry?Registry->FindPresenceStage(P.TargetStageId):nullptr;
 auto* House=Candidate.Houses.FindByPredicate([&](const auto& V){return V.Id==Header.Authority.IssuingHouseId;});
 const auto Funding=Candidate.InventoryLedger.CreateReadOnlyAccess().QueryInventory(P.FundingInventoryId);bool bOwned=false;
 if(Funding.IsSet()&&Funding->OwnerKind==EHansaInventoryOwnerKind::TradeStation){const auto* S=Candidate.TradeStations.FindByPredicate([&](const auto& V){return V.InventoryId==P.FundingInventoryId;});bOwned=S&&S->OwnerId==Header.Authority.IssuingHouseId;}
 if(Funding.IsSet()&&Funding->OwnerKind==EHansaInventoryOwnerKind::Vehicle){const auto* V=Candidate.Vehicles.FindByPredicate([&](const auto& X){return X.Id==Funding->VehicleId;});bOwned=V&&V->OwnerId==Header.Authority.IssuingHouseId;}
 if(Funding.IsSet()&&(Funding->OwnerKind==EHansaInventoryOwnerKind::Building||Funding->OwnerKind==EHansaInventoryOwnerKind::Warehouse)){const auto* B=Candidate.Buildings.FindByPredicate([&](const auto& X){return X.Id==Funding->BuildingId;});bOwned=B&&B->OwnerId==Header.Authority.IssuingHouseId;}
 if(!Presence||!Target||!House||!Funding.IsSet()||!bOwned||Presence->Upgrade.Status!=EHansaPresenceUpgradeStatus::Requested||Presence->Upgrade.TargetStageId!=P.TargetStageId) return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeStateInvalid,CommandIndex);
 if(House->Money.GetRawValue()<Target->UpgradeCostPfennig)return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeCostUnavailable,CommandIndex);
 for(const auto& Cost:Target->UpgradeGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId);const auto S=G?Candidate.InventoryLedger.CreateReadOnlyAccess().QueryStock(P.FundingInventoryId,G.Value):TOptional<FHansaInventoryStockProjection>();if(!G||!S.IsSet()||S->Available.GetRawValue()<Cost.QuantityMilliUnits)return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeCostUnavailable,CommandIndex);}
 House->Money=FHansaMoney::FromRaw(House->Money.GetRawValue()-Target->UpgradeCostPfennig);
 for(const auto& Cost:Target->UpgradeGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId).Value;const auto Tx=Candidate.InventoryLedger.TryTransfer(FHansaInventoryEndpoint::Inventory(P.FundingInventoryId),FHansaInventoryEndpoint::Sink(TEXT("PresenceUpgrade")),G,FHansaQuantity::FromRaw(Cost.QuantityMilliUnits),TickBefore,Candidate.InventoryLedger.CreateReadOnlyAccess().GetLastMovementSequence()+1);if(!Tx.IsSuccess())return MakeFailure(EHansaCommandGatewayError::PresenceUpgradeCostUnavailable,CommandIndex);}
 const auto Completion=FHansaSimulationTick::TryCreate(TickBefore.GetValue()+Target->UpgradeConstructionTicks);if(!Completion)return MakeFailure(EHansaCommandGatewayError::ClockOverflow,CommandIndex);
 Presence->Upgrade.Status=EHansaPresenceUpgradeStatus::Funded;Presence->Upgrade.FundingInventoryId=P.FundingInventoryId;Presence->Upgrade.FundedTick=TickBefore;Presence->Upgrade.CompletionTick=Completion.Value;Presence->Upgrade.SpentMoneyPfennig=Target->UpgradeCostPfennig;
 Presence->Contributions.InvestedPfennig=FMath::Min<int64>(MAX_int64,Presence->Contributions.InvestedPfennig+Target->UpgradeCostPfennig);
 Presence->History.Add({EHansaPresenceHistoryKind::UpgradeFunded,TickBefore,Event.GlobalSequence,P.TargetStageId,0,Target->UpgradeCostPfennig});
 Event.Type=EHansaDomainEventType::PresenceUpgradeFunded;Event.CityId=P.CityId;Event.Value=Target->UpgradeCostPfennig;break;
}
case EHansaGameplayCommandType::ApplyPresenceSpecialization:
{
 const auto& P=Command.GetApplyPresenceSpecialization();auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});
 const auto* Registry=Definitions.GetEconomicRegistry();const auto* Policy=Registry?Registry->FindCityTradePolicyForCity(P.CityId.ToString()):nullptr;const auto* Branch=Policy?Policy->Specializations.FindByPredicate([&](const auto& V){return V.SpecializationId==P.SpecializationId;}):nullptr;
 const auto* Stage=Presence&&Registry?Registry->FindPresenceStage(Presence->CurrentStageId):nullptr;const auto* Required=Branch&&Registry?Registry->FindPresenceStage(Branch->RequiredStageId):nullptr;
 if(!Presence||!Policy||!Branch||!Stage||!Required||Presence->Status!=EHansaForeignPresenceStatus::Active||Stage->Ordinal<Required->Ordinal)return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationUnavailable,CommandIndex);
 if(P.ReviewedRevision!=Presence->SpecializationRevision)return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationStaleReview,CommandIndex);
 const auto* Previous=Policy->Specializations.FindByPredicate([&](const auto& V){return V.ExclusiveGroupId==Branch->ExclusiveGroupId&&Presence->ActiveSpecializationIds.Contains(V.SpecializationId);});
 if((P.Action==EHansaPresenceSpecializationAction::Select&&Previous)||(P.Action==EHansaPresenceSpecializationAction::Respec&&(!Previous||!Previous->bAllowRespec)))return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationStateInvalid,CommandIndex);
 auto* House=Candidate.Houses.FindByPredicate([&](const auto& V){return V.Id==Header.Authority.IssuingHouseId;});const auto Funding=Candidate.InventoryLedger.CreateReadOnlyAccess().QueryInventory(P.FundingInventoryId);const auto* Station=Candidate.TradeStations.FindByPredicate([&](const auto& V){return V.InventoryId==P.FundingInventoryId;});
 if(!House||!Funding.IsSet()||!Station||Station->OwnerId!=Header.Authority.IssuingHouseId)return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationCostUnavailable,CommandIndex);
 const int64 Refund=Previous?Previous->InvestmentCostPfennig*Previous->RespecRefundBasisPoints/10000:0;const auto AvailableMoney=FHansaCheckedIntegerMath::TryAdd(House->Money.GetRawValue(),Refund);if(!AvailableMoney||AvailableMoney.Value<Branch->InvestmentCostPfennig)return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationCostUnavailable,CommandIndex);
 for(const auto& Cost:Branch->InvestmentGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId);const auto S=G?Candidate.InventoryLedger.CreateReadOnlyAccess().QueryStock(P.FundingInventoryId,G.Value):TOptional<FHansaInventoryStockProjection>();if(!G||!S.IsSet()||S->Available.GetRawValue()<Cost.QuantityMilliUnits)return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationCostUnavailable,CommandIndex);}
 House->Money=FHansaMoney::FromRaw(AvailableMoney.Value-Branch->InvestmentCostPfennig);for(const auto& Cost:Branch->InvestmentGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId).Value;const auto Tx=Candidate.InventoryLedger.TryTransfer(FHansaInventoryEndpoint::Inventory(P.FundingInventoryId),FHansaInventoryEndpoint::Sink(TEXT("PresenceSpecialization")),G,FHansaQuantity::FromRaw(Cost.QuantityMilliUnits),TickBefore,Candidate.InventoryLedger.CreateReadOnlyAccess().GetLastMovementSequence()+1);if(!Tx.IsSuccess())return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationCostUnavailable,CommandIndex);}
 if(Previous)Presence->ActiveSpecializationIds.Remove(Previous->SpecializationId);Presence->ActiveSpecializationIds.AddUnique(Branch->SpecializationId);Presence->ActiveSpecializationIds.Sort();
 Presence->GrantedCapabilityIds=Stage->GrantedCapabilityIds;for(const FString& Id:Presence->ActiveSpecializationIds)if(const auto* B=Policy->Specializations.FindByPredicate([&](const auto& V){return V.SpecializationId==Id;}))Presence->GrantedCapabilityIds.Append(B->GrantedCapabilityIds);Presence->GrantedCapabilityIds.RemoveAll([&](const FString& Id){return Policy->DeniedCapabilityIds.Contains(Id);});Presence->GrantedCapabilityIds.Sort();
 const int64 CapacityDelta=Branch->StorageCapacityBonusMilliUnits-(Previous?Previous->StorageCapacityBonusMilliUnits:0);if(CapacityDelta!=0){const auto I=Candidate.InventoryLedger.CreateReadOnlyAccess().QueryInventory(Station->InventoryId);const auto NewCapacity=I?FHansaCheckedIntegerMath::TryAdd(I->Capacity.GetRawValue(),CapacityDelta):THansaValueResult<int64>::Failure(EHansaValueError::InvalidFormat);if(!NewCapacity||NewCapacity.Value<I->UsedCapacity.GetRawValue()||!Candidate.InventoryLedger.TrySetCapacity(Station->InventoryId,FHansaQuantity::FromRaw(NewCapacity.Value)))return MakeFailure(EHansaCommandGatewayError::PresenceSpecializationStateInvalid,CommandIndex);}
 ++Presence->SpecializationRevision;Presence->History.Add({Previous?EHansaPresenceHistoryKind::SpecializationReversed:EHansaPresenceHistoryKind::SpecializationApplied,TickBefore,Event.GlobalSequence,Branch->SpecializationId,0,Branch->InvestmentCostPfennig-Refund});
 Event.Type=EHansaDomainEventType::PresenceSpecializationApplied;Event.CityId=P.CityId;Event.Value=Presence->SpecializationRevision;break;
}case EHansaGameplayCommandType::ManageCityPrivilege:
{
 const auto& P=Command.GetManageCityPrivilege();auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});const auto* Registry=Definitions.GetEconomicRegistry();const auto* Policy=Registry?Registry->FindCityTradePolicyForCity(P.CityId.ToString()):nullptr;const auto* Def=Policy?Policy->Privileges.FindByPredicate([&](const auto& V){return V.PrivilegeId==P.PrivilegeId;}):nullptr;const auto* Stage=Presence&&Registry?Registry->FindPresenceStage(Presence->CurrentStageId):nullptr;const auto* Required=Def&&Registry?Registry->FindPresenceStage(Def->RequiredStageId):nullptr;
 if(!Presence||!Policy||!Def||!Stage||!Required||Stage->Ordinal<Required->Ordinal||!Presence->GrantedCapabilityIds.Contains(TEXT("PresenceCapability.Privileges"))||P.ReviewedRevision!=Presence->AuthorityRevision)return MakeFailure(EHansaCommandGatewayError::CityPrivilegeUnavailable,CommandIndex);
 auto* Existing=Presence->Privileges.FindByPredicate([&](const auto& V){return V.PrivilegeId==P.PrivilegeId&&V.Status!=EHansaCityPrivilegeStatus::Revoked;});
 if(P.Action==EHansaCityPrivilegeAction::Revoke){auto* Lease=Existing?Candidate.LeasedPlots.FindByPredicate([&](const auto& V){return V.Id==Existing->GrantedLeaseId;}):nullptr;if(!Existing||!Def->bReversible||!Lease||!Lease->OccupyingBuildingIds.IsEmpty())return MakeFailure(EHansaCommandGatewayError::CityPrivilegeStateInvalid,CommandIndex);Existing->Status=EHansaCityPrivilegeStatus::Revoked;Lease->bActive=false;++Presence->AuthorityRevision;Event.Type=EHansaDomainEventType::CityPrivilegeRevoked;Event.CityId=P.CityId;break;}
 auto* House=Candidate.Houses.FindByPredicate([&](const auto& V){return V.Id==Header.Authority.IssuingHouseId;});const auto* Station=Candidate.TradeStations.FindByPredicate([&](const auto& V){return V.InventoryId==P.FundingInventoryId&&V.OwnerId==Header.Authority.IssuingHouseId;});if(Existing||!P.GrantedLeaseId.IsValid()||Candidate.LeasedPlots.ContainsByPredicate([&](const auto& V){return V.Id==P.GrantedLeaseId;})||!House||!Station||House->Money.GetRawValue()<Def->CostPfennig)return MakeFailure(EHansaCommandGatewayError::CityPrivilegeCostUnavailable,CommandIndex);
 for(const auto& Cost:Def->CostGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId);const auto S=G?Candidate.InventoryLedger.CreateReadOnlyAccess().QueryStock(P.FundingInventoryId,G.Value):TOptional<FHansaInventoryStockProjection>();if(!G||!S||S->Available.GetRawValue()<Cost.QuantityMilliUnits)return MakeFailure(EHansaCommandGatewayError::CityPrivilegeCostUnavailable,CommandIndex);}House->Money=FHansaMoney::FromRaw(House->Money.GetRawValue()-Def->CostPfennig);for(const auto& Cost:Def->CostGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId).Value;if(!Candidate.InventoryLedger.TryTransfer(FHansaInventoryEndpoint::Inventory(P.FundingInventoryId),FHansaInventoryEndpoint::Sink(TEXT("CityPrivilege")),G,FHansaQuantity::FromRaw(Cost.QuantityMilliUnits),TickBefore,Candidate.InventoryLedger.CreateReadOnlyAccess().GetLastMovementSequence()+1).IsSuccess())return MakeFailure(EHansaCommandGatewayError::CityPrivilegeCostUnavailable,CommandIndex);}
 FHansaLeasedPlotState Lease;Lease.Id=P.GrantedLeaseId;Lease.StationId=Station->Id;Lease.OwnerId=Header.Authority.IssuingHouseId;Lease.CityId=P.CityId;Lease.SiteId=TEXT("Privilege.")+P.PrivilegeId;Lease.PlotCategory=TEXT("Commercial");Lease.BoundsMin=Def->LeaseBoundsMin;Lease.BoundsMax=Def->LeaseBoundsMax;Lease.PermittedBuildingCategories=Def->PermittedBuildingCategories;Lease.bActive=true;Candidate.LeasedPlots.Add(Lease);Candidate.LeasedPlots.Sort([](const auto& L,const auto& R){return L.Id<R.Id;});FHansaCityPrivilegeState Granted;Granted.PrivilegeId=P.PrivilegeId;Granted.GrantedLeaseId=P.GrantedLeaseId;Granted.GrantedTick=TickBefore;Granted.ExpiryTick=FHansaSimulationTick::TryCreate(Def->DurationTicks==0?MAX_int64:TickBefore.GetValue()+Def->DurationTicks).Value;Granted.SpentMoneyPfennig=Def->CostPfennig;Presence->Privileges.Add(Granted);Presence->Privileges.Sort([](const auto& L,const auto& R){return L.PrivilegeId<R.PrivilegeId;});++Presence->AuthorityRevision;Event.Type=EHansaDomainEventType::CityPrivilegeGranted;Event.CityId=P.CityId;Event.Value=Def->CostPfennig;break;
}
case EHansaGameplayCommandType::FundCityProject:
{
 const auto& P=Command.GetFundCityProject();auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});const auto* Registry=Definitions.GetEconomicRegistry();const auto* Policy=Registry?Registry->FindCityTradePolicyForCity(P.CityId.ToString()):nullptr;const auto* Def=Policy?Policy->CityProjects.FindByPredicate([&](const auto& V){return V.ProjectId==P.ProjectId;}):nullptr;const auto* Stage=Presence&&Registry?Registry->FindPresenceStage(Presence->CurrentStageId):nullptr;const auto* Required=Def&&Registry?Registry->FindPresenceStage(Def->RequiredStageId):nullptr;
 if(!Presence||!Def||!Stage||!Required||Stage->Ordinal<Required->Ordinal||!Presence->GrantedCapabilityIds.Contains(TEXT("PresenceCapability.CityProjects"))||P.ReviewedRevision!=Presence->AuthorityRevision||Presence->CityProjects.ContainsByPredicate([&](const auto& V){return V.ProjectId==P.ProjectId;}))return MakeFailure(EHansaCommandGatewayError::CityProjectUnavailable,CommandIndex);
 auto* House=Candidate.Houses.FindByPredicate([&](const auto& V){return V.Id==Header.Authority.IssuingHouseId;});const auto* Station=Candidate.TradeStations.FindByPredicate([&](const auto& V){return V.InventoryId==P.FundingInventoryId&&V.OwnerId==Header.Authority.IssuingHouseId;});if(!House||!Station||House->Money.GetRawValue()<Def->CostPfennig)return MakeFailure(EHansaCommandGatewayError::CityProjectCostUnavailable,CommandIndex);for(const auto& Cost:Def->CostGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId);const auto S=G?Candidate.InventoryLedger.CreateReadOnlyAccess().QueryStock(P.FundingInventoryId,G.Value):TOptional<FHansaInventoryStockProjection>();if(!G||!S||S->Available.GetRawValue()<Cost.QuantityMilliUnits)return MakeFailure(EHansaCommandGatewayError::CityProjectCostUnavailable,CommandIndex);}House->Money=FHansaMoney::FromRaw(House->Money.GetRawValue()-Def->CostPfennig);for(const auto& Cost:Def->CostGoods){const auto G=FHansaGoodId::TryParse(Cost.GoodId).Value;if(!Candidate.InventoryLedger.TryTransfer(FHansaInventoryEndpoint::Inventory(P.FundingInventoryId),FHansaInventoryEndpoint::Sink(TEXT("CityProject")),G,FHansaQuantity::FromRaw(Cost.QuantityMilliUnits),TickBefore,Candidate.InventoryLedger.CreateReadOnlyAccess().GetLastMovementSequence()+1).IsSuccess())return MakeFailure(EHansaCommandGatewayError::CityProjectCostUnavailable,CommandIndex);}FHansaCityProjectState Project;Project.ProjectId=P.ProjectId;Project.FundedTick=TickBefore;Project.CompletionTick=FHansaSimulationTick::TryCreate(TickBefore.GetValue()+Def->ConstructionTicks).Value;Project.SpentMoneyPfennig=Def->CostPfennig;Presence->CityProjects.Add(Project);Presence->CityProjects.Sort([](const auto& L,const auto& R){return L.ProjectId<R.ProjectId;});++Presence->AuthorityRevision;Event.Type=EHansaDomainEventType::CityProjectFunded;Event.CityId=P.CityId;Event.Value=Def->CostPfennig;break;
}
case EHansaGameplayCommandType::TransitionCityAuthority:
{
 const auto& P=Command.GetTransitionCityAuthority();auto* Presence=Candidate.ForeignPresences.FindByPredicate([&](const auto& V){return V.HouseId==Header.Authority.IssuingHouseId&&V.CityId==P.CityId;});const auto* Registry=Definitions.GetEconomicRegistry();const auto* Policy=Registry?Registry->FindCityTradePolicyForCity(P.CityId.ToString()):nullptr;if(!Presence||!Policy||Presence->bGovernanceAuthority||P.ReviewedRevision!=Presence->AuthorityRevision||Presence->CurrentStageId!=TEXT("PresenceStage.PrivilegedPresence"))return MakeFailure(EHansaCommandGatewayError::GovernanceTransitionUnavailable,CommandIndex);if(!Policy->bExceptionalGovernanceAllowed||Policy->GovernanceCharterId!=P.CharterId||!Policy->GovernanceScenarioIds.Contains(Definitions.GetScenarioId().ToString()))return MakeFailure(EHansaCommandGatewayError::GovernanceScenarioGateRejected,CommandIndex);const auto* Target=Registry->FindPresenceStage(TEXT("PresenceStage.ExceptionalGovernance"));if(!Target)return MakeFailure(EHansaCommandGatewayError::InvalidDefinitionContext,CommandIndex);Presence->CurrentStageId=Target->StableId;Presence->GrantedCapabilityIds=Target->GrantedCapabilityIds;Presence->bGovernanceAuthority=true;Presence->GovernanceCharterId=P.CharterId;Presence->GovernanceGrantedTick=TickBefore;++Presence->AuthorityRevision;Event.Type=EHansaDomainEventType::CityAuthorityTransitioned;Event.CityId=P.CityId;Event.Value=1;break;
}
