"""Offline native trade-chart mesh from the repository's public-domain Natural Earth source.
No raster generation, downloads or gameplay state changes. Run with Python 3.12.
"""
from pathlib import Path
import hashlib
import sys
import zipfile
import io
import json
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / 'Saved/GenerationJobs/HansaWorld_20260918/python'))
import shapefile
from shapely.geometry import shape, box
from shapely import constrained_delaunay_triangles

source = root / 'SourceArt/Terrain/HansaWorld/Prototype_20260918/sources/land.zip'
archive = zipfile.ZipFile(source)
def part(extension):
    return io.BytesIO(archive.read(next(n for n in archive.namelist() if n.endswith(extension))))
reader = shapefile.Reader(shp=part('.shp'), shx=part('.shx'), dbf=part('.dbf'))
extent = box(-1, 50, 32, 61)
polygons = []
for item in reader.iterShapes():
    geometry = shape(item.__geo_interface__)
    if not geometry.intersects(extent):
        continue
    clipped = geometry.intersection(extent).simplify(.025, preserve_topology=True)
    polygons.extend([clipped] if clipped.geom_type == 'Polygon' else [p for p in clipped.geoms if p.geom_type == 'Polygon'])
points, indices, outlines = [], [], []
for polygon in polygons:
    if polygon.area < .003:
        continue
    for triangle in constrained_delaunay_triangles(polygon).geoms:
        for x, y in list(triangle.exterior.coords)[:3]:
            indices.append(len(points))
            points.append(((x+1)/33, (61-y)/11))
    for ring in [polygon.exterior, *polygon.interiors]:
        outlines.append([((x+1)/33, (61-y)/11) for x,y in ring.coords])
assert len(points) < 65535
lines = ['// Generated by Scripts/BuildTradeChart.py. Natural Earth 1:10m land, public domain.',
         '// Modern coastline, geographic context only; not medieval reconstruction or ship pathfinding.',
         '// Source SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
         'static const FVector2f TradeLandVertices[] = {']
lines += [f'{{{x:.7f}f,{y:.7f}f}},' for x,y in points]
lines += ['};', 'static const TArray<TArray<FVector2D>> TradeCoastlines = {']
lines += ['{' + ','.join(f'{{{x:.7f},{y:.7f}}}' for x,y in ring) + '},' for ring in outlines]
lines += ['};', '']
output = root / 'Source/Hansa/Private/UI/HansaTradeChartData.inl'
output.write_text('\n'.join(lines), encoding='utf-8')
print(f'{len(points)//3} triangles, {len(outlines)} coastline rings: {output}')
# Rivers are geographic context, never an assertion of navigability.
archive = zipfile.ZipFile(root / 'SourceArt/Terrain/HansaWorld/Prototype_20260918/sources/rivers.zip')
reader = shapefile.Reader(shp=part('.shp'), shx=part('.shx'), dbf=part('.dbf'))
rivers = []
for item in reader.iterShapes():
    geometry = shape(item.__geo_interface__)
    if not geometry.intersects(extent):
        continue
    clipped = geometry.intersection(extent).simplify(.012, preserve_topology=True)
    pieces = [clipped] if clipped.geom_type == 'LineString' else list(getattr(clipped, 'geoms', []))
    for line in pieces:
        if line.geom_type == 'LineString' and line.length > .1:
            rivers.append([((x+1)/33, (61-y)/11) for x,y in line.coords])
with output.open('a', encoding='utf-8') as f:
    f.write('static const TArray<TArray<FVector2D>> TradeRivers = {\n')
    for river in rivers:
        f.write('{' + ','.join(f'{{{x:.7f},{y:.7f}}}' for x,y in river) + '},\n')
    f.write('};\n')
manifest = json.loads((root / 'SourceArt/UI/TradeWorkspace/Geography/reviewed-city-locations.json').read_text(encoding='utf-8'))
city_lines = ['// Generated from SourceArt/UI/TradeWorkspace/Geography/reviewed-city-locations.json.',
              '// GeoNames CC BY 4.0 (https://www.geonames.org/), reviewed approximate centres; not navigation data.',
              'static const TMap<FString,FVector2D> TradeCityLocations = {']
for city in manifest['cities']:
    city_lines.append('{TEXT("%s"),FVector2D(%.7f,%.7f)},' % (city['id'], (city['longitude']+1)/33, (61-city['latitude'])/11))
city_lines += ['};', '']
(output.parent / 'HansaTradeCityLocations.inl').write_text('\n'.join(city_lines), encoding='utf-8')
