"""Generate deterministic 4m placement terrain from the existing native-water source.

No Landscape, water actor, raster artwork or measured elevation is edited.
River point[3] is the full width consumed by build_water.py; segments are linear.
"""
import hashlib
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "SourceArt/Terrain/Lubeck/Survey_20260907/hydrology/water-build.json"
OUT = ROOT / "Source/Hansa/Private/World/HansaLubeckSurveyPlacement.generated.inl"
MIN_X, MAX_X, MIN_Y, MAX_Y = -473, 533, -484, 522
xs = -12000 + (np.arange(MIN_X, MAX_X + 1) + .5) * 400
ys = -8000 + (np.arange(MIN_Y, MAX_Y + 1) + .5) * 400
water = np.zeros((len(xs), len(ys)), dtype=bool)

for body in json.loads(SOURCE.read_text(encoding="utf-8"))["bodies"]:
    points = np.asarray(body["points"], dtype=float)
    if body["type"] == "river":
        for a, b in zip(points[:-1], points[1:]):
            radius = max(a[3], b[3]) / 2
            ix = np.flatnonzero((xs >= min(a[0], b[0])-radius) & (xs <= max(a[0], b[0])+radius))
            iy = np.flatnonzero((ys >= min(a[1], b[1])-radius) & (ys <= max(a[1], b[1])+radius))
            if not len(ix) or not len(iy):
                continue
            x, y = xs[ix, None], ys[None, iy]
            dx, dy = b[0]-a[0], b[1]-a[1]
            t = np.clip(((x-a[0])*dx + (y-a[1])*dy) / max(dx*dx+dy*dy, 1), 0, 1)
            r = (a[3] + t*(b[3]-a[3])) / 2
            water[np.ix_(ix, iy)] |= (x-a[0]-t*dx)**2 + (y-a[1]-t*dy)**2 <= r*r
    else:
        ix = np.flatnonzero((xs >= points[:,0].min()) & (xs <= points[:,0].max()))
        iy = np.flatnonzero((ys >= points[:,1].min()) & (ys <= points[:,1].max()))
        x, y = xs[ix, None], ys[None, iy]
        inside = np.zeros((len(ix), len(iy)), dtype=bool)
        for a, b in zip(points, np.roll(points, -1, axis=0)):
            if a[1] == b[1]:
                continue
            inside ^= ((a[1] > y) != (b[1] > y)) & (x < (b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])
        water[np.ix_(ix, iy)] |= inside

shore = np.zeros_like(water)
shore[1:] |= water[:-1]
shore[:-1] |= water[1:]
shore[:,1:] |= water[:,:-1]
shore[:,:-1] |= water[:,1:]
terrain = np.where(water, 2, np.where(shore, 1, 0))
# A three-by-two fishery with water east, land west and space for its road/market.
candidates = []
for i, j in np.argwhere((terrain == 1) & (np.abs(xs[:,None]) < 80000) & (np.abs(ys[None,:]) < 80000)):
    i, j = int(i)-2, int(j)
    if i < 14 or j < 6 or i+3 >= len(xs) or j+6 >= len(ys):
        continue
    if np.any(water[i:i+3,j:j+2]) or not np.any(water[i+3,j:j+2]):
        continue
    if np.any(terrain[i-12:i,j-5:j+6] != 0):
        continue
    candidates.append((xs[i]**2 + ys[j]**2, i, j))
assert candidates, "No broad, fishery-compatible founding bank found"
_, start_i, start_j = min(candidates)
runs = []
for i, row in enumerate(terrain):
    edges = np.flatnonzero(np.r_[True, row[1:] != row[:-1], True])
    for first, end in zip(edges[:-1], edges[1:]):
        if row[first]:
            runs.append(f"    {{{i+MIN_X}, {first+MIN_Y}, {end-1+MIN_Y}, {int(row[first])}}},")
header = [
    "// Generated by Scripts/GenerateLubeckSurveyPlacement.py; do not hand edit.",
    "// Source: OpenStreetMap contributors, ODbL; existing native-water draft geometry.",
    "// https://www.openstreetmap.org/copyright",
    "// Source SHA256: " + hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
    "struct FSurveyTerrainRun { int32 X, FirstY, LastY; uint8 Terrain; };",
    f"static constexpr int32 SurveyFisheryX = {start_i+MIN_X};",
    f"static constexpr int32 SurveyFisheryY = {start_j+MIN_Y};",
    "static constexpr FSurveyTerrainRun SurveyTerrainRuns[] = {",
    *runs,
    "};",
]
OUT.write_text("\n".join(header)+"\n", encoding="utf-8")
print(json.dumps({"cells":int(terrain.size), "water":int(water.sum()), "shore":int((terrain==1).sum()),
    "runs":len(runs), "fishery":[start_i+MIN_X,start_j+MIN_Y],
    "focus_cm":[float(xs[start_i]-2000),float(ys[start_j])]}))
