"""Compile the placed-tree inventory into deterministic, shipping-safe resource cells.
Run after authoring/repositioning trees; --check verifies the checked-in runtime survey.
No provider paths or source art are loaded at runtime.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "SourceArt/Generated/Trees/LubeckSummer/v1/placement/placed_trees.json"
OUTPUT = ROOT / "Source/Hansa/Private/World/HansaLubeckTrees.generated.inl"

def generate():
    source = SOURCE.read_bytes()
    trees = json.loads(source)
    cells = set()
    ids = set()
    for tree in trees:
        if tree["id"] in ids:
            raise ValueError("Duplicate tree identity: " + tree["id"])
        ids.add(tree["id"])
        x, y = float(tree["x"]), float(tree["y"])
        if not math.isfinite(x) or not math.isfinite(y):
            raise ValueError("Non-finite tree location")
        cell = (math.floor((x + 12000) / 400), math.floor((y + 8000) / 400))
        if not (-473 <= cell[0] <= 533 and -484 <= cell[1] <= 522):
            raise ValueError("Tree outside surveyed map")
        cells.add(cell)
    if not cells:
        raise ValueError("Tree inventory is empty")
    lines = [
        "// Generated by Scripts/GenerateLubeckTreeResources.py; do not hand edit.",
        "// Source SHA-256: " + hashlib.sha256(source).hexdigest(),
        "static const Hansa::Simulation::FHansaGridCoordinate SurveyTreeCells[] = {",
    ]
    lines += ["    {%d, %d}," % cell for cell in sorted(cells)]
    lines += ["};", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != result:
            raise SystemExit("Tree resource survey is stale; regenerate it.")
        print("Tree resource survey matches authored trees.")
    else:
        OUTPUT.write_text(result, encoding="utf-8")
        print("Wrote", OUTPUT)
