"""Bake campaign map positions from existing terrain and reviewed city geography.

Uses the terrain job's pyproj installation; performs no downloads.
"""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / "Saved/GenerationJobs/HansaWorld_20260918/python"))
from pyproj import Transformer

manifest = json.loads((root / "SourceArt/Terrain/HansaWorld/Prototype_20260918/terrain-manifest.json").read_text(encoding="utf-8"))
reviewed = json.loads((root / "SourceArt/UI/TradeWorkspace/Geography/reviewed-city-locations.json").read_text(encoding="utf-8"))
seeds = {city["id"]: city for city in manifest["cities"]}
transform = Transformer.from_crs("EPSG:4326", manifest["crs"], always_xy=True)
west, _, _, north = manifest["projected_bounds_m"]
lines = [
    "// Generated by Scripts/PrepareMinimapCityLocations.py; do not edit.",
    "// Terrain EPSG:3035, 40:1 compression, X east / Y south. Seed centres stay fixed under radial warps.",
    "// Reviewed supplementary locations: GeoNames CC BY 4.0, https://www.geonames.org/.",
    "static const TMap<FName,FVector2D> CampaignCityLocations = {",
]
for city in reviewed["cities"]:
    seed = seeds.get(city["id"])
    if seed:
        x, y = seed["x_cm"], seed["y_cm"]
    else:
        east, northing = transform.transform(city["longitude"], city["latitude"])
        x = (east - west) / manifest["compression"] * 100
        y = (north - northing) / manifest["compression"] * 100
        # Supplementary cities must lie outside the authored local city warps.
        assert all(((x-s["x_cm"])**2 + (y-s["y_cm"])**2)**.5 > s["transition_radius_m"]*100 for s in seeds.values())
    lines.append(f' {{TEXT("{city["id"]}"),FVector2D({x:.9f},{y:.9f})}},')
lines.append("};")
destination = root / "Source/Hansa/Private/UI/HansaMinimapCityLocations.inl"
destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Saved {len(reviewed['cities'])} campaign city locations: {destination}")
