#include "Commands/HansaGameplayCommandGateway.h"
#include "Definitions/HansaEconomicDefinitionCompiler.h"
#include "Definitions/HansaEconomicDefinitionSeeder.h"
#include "Definitions/HansaSimulationDefinitionContext.h"
#include "Misc/AutomationTest.h"
#include "Queries/HansaSimulationReadOnly.h"
#include "Save/HansaSaveEnvelope.h"
#include "Systems/HansaSimulationPipeline.h"

#if WITH_DEV_AUTOMATION_TESTS
namespace Hansa::Editor::Tests::TradePresence
{
 using namespace Hansa::Simulation;
 IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHansaLeasedForeignConstructionTest,
  "Hansa.Integration.TradePresence.LeasedForeignConstruction",
  EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

 bool FHansaLeasedForeignConstructionTest::RunTest(const FString& Parameters)
 {
  auto Owned=EconomicDefinitions::CreateMvpDefinitionSet(GetTransientPackage());TArray<const UHansaDefinitionBase*> Raw;for(const auto& V:Owned)Raw.Add(V.Get());
  auto Compiled=FHansaEconomicDefinitionCompiler::Compile(Raw);if(!TestTrue(TEXT("Prompt 9 catalog compiles"),Compiled.IsValid()))return false;
  const auto ScenarioId=FHansaScenarioId::TryParse(TEXT("Scenario.LubeckGrainShortageV1")).Value;const uint64 RegistryHash=Compiled.Registry.GetRegistryHash();const FHansaEconomicRegistry* Registry=&Compiled.Registry;
  const auto Player=FHansaHouseId::TryCreate(1).Value;const auto CityOwner=FHansaHouseId::TryCreate(2).Value;const auto City=FHansaCityDefinitionId::TryParse(TEXT("City.Rostock")).Value;
  const auto Market=FHansaBuildingTypeId::TryParse(TEXT("Building.Market")).Value;const auto Road=FHansaBuildingTypeId::TryParse(TEXT("Building.Road")).Value;const auto Planks=FHansaGoodId::TryParse(TEXT("Good.Planks")).Value;const auto Tools=FHansaGoodId::TryParse(TEXT("Good.Tools")).Value;
  const auto StationId=FHansaTradeStationId::TryCreate(1).Value;const auto InventoryId=FHansaInventoryId::TryCreate(1).Value;const auto LeaseId=FHansaLeasedPlotId::TryCreate(1).Value;
  FHansaSimulationInitialization I;I.Clock=FHansaSimulationClock::TryCreate(FHansaSimulationVersion::TryCreate(1).Value,FHansaSimulationTick()).Value;I.CampaignSeed=90909;I.Houses={{Player,FHansaMoney::FromRaw(100000)},{CityOwner,FHansaMoney::FromRaw(0)}};I.Cities.Add({City,{}});
  const auto* Quarter=Registry->FindPresenceStage(TEXT("PresenceStage.MerchantQuarter"));FHansaForeignPresenceState Presence;Presence.HouseId=Player;Presence.CityId=City;Presence.CurrentStageId=Quarter->StableId;Presence.GrantedCapabilityIds=Quarter->GrantedCapabilityIds;Presence.GrantedCapabilityIds.Sort();Presence.StationId=StationId;Presence.LeasedPlotId=LeaseId;I.ForeignPresences.Add(Presence);
  FHansaTradeStationState Station;Station.Id=StationId;Station.OwnerId=Player;Station.CityId=City;Station.SiteId=TEXT("TradeStationSite.Rostock.Harbor.01");Station.InventoryId=InventoryId;Station.FactorId=FHansaFactorId::TryCreate(1).Value;Station.LeasedPlotId=LeaseId;Station.Status=EHansaTradeStationStatus::Active;I.TradeStations.Add(Station);
  FHansaLeasedPlotState Lease;Lease.Id=LeaseId;Lease.StationId=StationId;Lease.OwnerId=Player;Lease.CityId=City;Lease.SiteId=Station.SiteId;Lease.PlotCategory=TEXT("Commercial");Lease.BoundsMin={8,8};Lease.BoundsMax={19,19};Lease.PermittedBuildingCategories={TEXT("Commercial"),TEXT("Production"),TEXT("Storage")};Lease.bActive=true;Lease.bOccupied=true;I.LeasedPlots.Add(Lease);
  FHansaInventoryInitialization Storage;Storage.Id=InventoryId;Storage.OwnerKind=EHansaInventoryOwnerKind::TradeStation;Storage.CityId=City;Storage.TradeStationId=StationId;Storage.Capacity=FHansaQuantity::FromRaw(100000);Storage.AcceptedGoods={Planks,Tools};Storage.InitialStock={{Planks,FHansaQuantity::FromRaw(20000)},{Tools,FHansaQuantity::FromRaw(5000)}};I.Inventories.Add(Storage);
  FHansaPlacementMapInitialization Map;Map.CityId=City;Map.BoundsMin={0,0};Map.BoundsMax={30,30};Map.RoadBuildingDefinitionId=Road;for(int32 X=0;X<=30;++X)for(int32 Y=0;Y<=30;++Y)Map.Cells.Add({{X,Y},EHansaPlacementTerrain::Land,CityOwner,false});I.Placement.Maps.Add(Map);I.Placement.Entitlements.Add({Player,Market});TArray<FHansaPlacementMapInitialization> TopologyMaps;TopologyMaps.Add(MoveTemp(Map));auto Topology=FHansaPlacementTopology::TryCreate(MoveTemp(TopologyMaps));if(!TestTrue(TEXT("Prompt 9 topology compiles"),Topology.IsSuccess()))return false;auto DefinitionsResult=FHansaSimulationDefinitionContext::TryCreate(ScenarioId,RegistryHash,MoveTemp(Compiled.Registry),MoveTemp(Topology.Value));if(!TestTrue(TEXT("Prompt 9 definition context compiles"),DefinitionsResult.IsSuccess()))return false;auto Definitions=MoveTemp(DefinitionsResult.Value);Registry=Definitions.GetEconomicRegistry();
  FHansaBuildingState RoadBuilding;RoadBuilding.Id=FHansaBuildingId::TryCreate(1).Value;RoadBuilding.DefinitionId=Road;RoadBuilding.OwnerId=CityOwner;RoadBuilding.ConstructionProgress=FHansaRate::FromPartsPerMillion(FHansaRate::Scale);RoadBuilding.ConstructionState=EHansaConstructionState::Completed;I.Buildings.Add(RoadBuilding);
  FHansaPlacedBuildingRecord RoadPlacement;RoadPlacement.BuildingId=RoadBuilding.Id;RoadPlacement.OwnerId=CityOwner;RoadPlacement.Spec={City,Road,{8,7},EHansaGridRotation::North};RoadPlacement.OccupiedCells={{8,7},{9,7},{10,7}};I.Placement.Placements.Add(RoadPlacement);
  auto Made=FHansaSimulationState::TryCreate(MoveTemp(I));if(!TestTrue(TEXT("Bounded foreign construction fixture validates"),Made.IsSuccess()))return false;FHansaSimulationState State=MoveTemp(Made.Value);FHansaSimulationTransientCache Cache;uint64 Seq=1;
  auto Submit=[&](FHansaGridCoordinate Anchor,FHansaBuildingId Id){FHansaCommandHeader H;H.CommandId=FHansaCommandId::TryCreate(Seq).Value;H.GlobalSequence=Seq++;H.Authority={Player,1,EHansaCommandOrigin::ControlledAutomation};H.RequestedExecutionTick=State.CreateReadOnlyAccess(Definitions).GetClock().GetTick();FHansaPlaceBuildingCommand P;P.BuildingId=Id;P.Placement={City,Market,Anchor,EHansaGridRotation::North};auto C=FHansaGameplayCommand::Create(H,P);return FHansaGameplayCommandGateway::ExecuteTick(State,Definitions,MakeArrayView(&C,1),Cache);};
  const int64 MoneyBefore=State.CreateReadOnlyAccess(Definitions).GetHouses()[0].Money.GetRawValue();const int64 PlanksBefore=State.CreateReadOnlyAccess(Definitions).GetInventories().QueryStock(InventoryId,Planks)->Stock.GetRawValue();
  const auto Accepted=Submit({8,8},FHansaBuildingId::TryCreate(2).Value);TestTrue(TEXT("Authorized market constructs wholly inside active leased plot"),Accepted.IsSuccess());auto Read=State.CreateReadOnlyAccess(Definitions);TestEqual(TEXT("Foreign build charges the player house"),Read.GetHouses()[0].Money.GetRawValue(),MoneyBefore-1800);TestEqual(TEXT("Foreign build consumes player station materials"),Read.GetInventories().QueryStock(InventoryId,Planks)->Stock.GetRawValue(),PlanksBefore-6000);TestTrue(TEXT("City-owned road remains owned by the city"),Read.GetBuildings().ContainsByPredicate([&](const auto& V){return V.Id==RoadBuilding.Id&&V.OwnerId==CityOwner;}));
  FHansaSaveSnapshot Snapshot;Snapshot.State=State;Snapshot.BuildVersion=TEXT("TR-09-Test");Snapshot.SavedUtc=TEXT("2026-09-21T00:00:00Z");Snapshot.Players={{1,Player}};TArray<uint8> Bytes;const auto Encoded=FHansaSaveEnvelope::Encode(Snapshot,Definitions,Bytes);if(!TestTrue(*Encoded.Message,Encoded.IsSuccess()))return false;FHansaSaveSnapshot Loaded;const auto Decoded=FHansaSaveEnvelope::Decode(Bytes,Definitions,Loaded);if(!TestTrue(*Decoded.Message,Decoded.IsSuccess()))return false;TestEqual(TEXT("Foreign building and lease occupancy survive save/reload"),Loaded.State.CreateReadOnlyAccess(Definitions).GetFingerprint().Value,Read.GetFingerprint().Value);
  const auto Overlays=Read.BuildLeasedPlotOverlayProjection(Player,City);TestTrue(TEXT("Overlay identifies occupied player construction with a non-color pattern"),Overlays.Num()==1&&Overlays[0].Kind==EHansaLeasedPlotOverlayKind::Owned&&!Overlays[0].PatternKey.IsEmpty()&&!Overlays[0].Label.IsEmpty());const auto Browser=Read.BuildForeignConstructionBrowser(Player,City);TestEqual(TEXT("Browser exposes the three approved choices"),Browser.Num(),3);TestTrue(TEXT("Browser filters choices through actual permissions"),!Browser.ContainsByPredicate([](const auto& V){return !V.bPermitted||V.Reason.IsEmpty();}));
  const uint64 BeforeRejected=Read.GetFingerprint().Value;const auto Rejected=Submit({18,18},FHansaBuildingId::TryCreate(3).Value);TestEqual(TEXT("Footprint crossing the lease boundary rejects"),Rejected.GetError(),EHansaCommandGatewayError::PlacementRejected);TestEqual(TEXT("Boundary rejection is precise"),Rejected.GetPlacementValidation().GetValue().GetPrimaryFailure(),EHansaPlacementFailure::ForeignLeaseBoundary);TestEqual(TEXT("Rejected foreign placement rolls back all state"),State.CreateReadOnlyAccess(Definitions).GetFingerprint().Value,BeforeRejected);
  auto Suspended=Lease;Suspended.bActive=false;auto Office=Presence;const auto* OfficeStage=Registry->FindPresenceStage(TEXT("PresenceStage.MerchantOffice"));Office.CurrentStageId=OfficeStage->StableId;Office.GrantedCapabilityIds=OfficeStage->GrantedCapabilityIds;
  const auto& Placement=State.CreateReadOnlyAccess(Definitions).GetPlacement();FHansaPlacementSpec Candidate{City,Market,{12,8},EHansaGridRotation::North};
  TestEqual(TEXT("Suspended rights have a distinct cause"),FHansaPlacementRules::Validate(Placement,*Registry,Player,Candidate,MakeArrayView(&Presence,1),MakeArrayView(&Suspended,1)).GetPrimaryFailure(),EHansaPlacementFailure::ForeignLeaseSuspended);
  TestEqual(TEXT("Merchant office stage cannot use merchant-quarter construction"),FHansaPlacementRules::Validate(Placement,*Registry,Player,Candidate,MakeArrayView(&Office,1),MakeArrayView(&Lease,1)).GetPrimaryFailure(),EHansaPlacementFailure::ForeignPresenceStageInsufficient);
  auto Denied=Lease;Denied.PermittedBuildingCategories={TEXT("Production")};TestEqual(TEXT("Wrong building category rejects precisely"),FHansaPlacementRules::Validate(Placement,*Registry,Player,Candidate,MakeArrayView(&Presence,1),MakeArrayView(&Denied,1)).GetPrimaryFailure(),EHansaPlacementFailure::ForeignBuildingCategoryDenied);
  return !HasAnyErrors();
 }
}
#endif