namespace Hansa::Editor::Tests::TradePresence {
using namespace Hansa::Simulation;
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHansaCityPrivilegeProjectAuthorityTest,"Hansa.Integration.TradePresence.CityPrivilegeProjectAndAuthority",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHansaCityPrivilegeProjectAuthorityTest::RunTest(const FString& Parameters)
{
 auto Owned=EconomicDefinitions::CreateMvpDefinitionSet(GetTransientPackage());TArray<const UHansaDefinitionBase*> Raw;for(const auto& V:Owned)Raw.Add(V.Get());auto C=FHansaEconomicDefinitionCompiler::Compile(Raw);if(!TestTrue(TEXT("catalog"),C.IsValid()))return false;auto D=FHansaSimulationDefinitionContext::TryCreate(FHansaScenarioId::TryParse(TEXT("Scenario.LubeckGrainShortageV1")).Value,C.Registry.GetRegistryHash(),MoveTemp(C.Registry)).Value;const auto* Rg=D.GetEconomicRegistry();
 const auto H=FHansaHouseId::TryCreate(1).Value;const auto R=FHansaCityDefinitionId::TryParse(TEXT("City.Rostock")).Value;const auto GCity=FHansaCityDefinitionId::TryParse(TEXT("City.Hamburg")).Value;const auto SId=FHansaTradeStationId::TryCreate(1).Value;const auto IId=FHansaInventoryId::TryCreate(1).Value;const auto MId=FHansaInventoryId::TryCreate(2).Value;const auto L1=FHansaLeasedPlotId::TryCreate(1).Value;const auto L2=FHansaLeasedPlotId::TryCreate(2).Value;const auto P=FHansaGoodId::TryParse(TEXT("Good.Planks")).Value;const auto B=FHansaGoodId::TryParse(TEXT("Good.Bread")).Value;const auto* Stage=Rg->FindPresenceStage(TEXT("PresenceStage.PrivilegedPresence"));FHansaSimulationInitialization X;X.Clock=FHansaSimulationClock::TryCreate(FHansaSimulationVersion::TryCreate(1).Value,FHansaSimulationTick()).Value;X.CampaignSeed=10;X.Houses.Add({H,FHansaMoney::FromRaw(500000)});X.Cities.Add({R,{}});X.Cities.Add({GCity,{}});FHansaForeignPresenceState FP;FP.HouseId=H;FP.CityId=R;FP.CurrentStageId=Stage->StableId;FP.GrantedCapabilityIds=Stage->GrantedCapabilityIds;FP.StationId=SId;FP.LeasedPlotId=L1;X.ForeignPresences.Add(FP);FHansaForeignPresenceState GovernancePresence=FP;GovernancePresence.CityId=GCity;GovernancePresence.StationId={};GovernancePresence.LeasedPlotId={};X.ForeignPresences.Add(GovernancePresence);FHansaTradeStationState S;S.Id=SId;S.OwnerId=H;S.CityId=R;S.SiteId=TEXT("TradeStationSite.Rostock.Harbor.01");S.InventoryId=IId;S.FactorId=FHansaFactorId::TryCreate(1).Value;S.LeasedPlotId=L1;S.Status=EHansaTradeStationStatus::Active;X.TradeStations.Add(S);FHansaLeasedPlotState L;L.Id=L1;L.StationId=SId;L.OwnerId=H;L.CityId=R;L.SiteId=S.SiteId;L.PlotCategory=TEXT("Commercial");L.BoundsMin={8,8};L.BoundsMax={19,19};L.PermittedBuildingCategories={TEXT("Storage"),TEXT("Commercial")};L.bActive=true;X.LeasedPlots.Add(L);
 FHansaInventoryInitialization SI;SI.Id=IId;SI.OwnerKind=EHansaInventoryOwnerKind::TradeStation;SI.CityId=R;SI.TradeStationId=SId;SI.Capacity=FHansaQuantity::FromRaw(50000);SI.AcceptedGoods={P};SI.InitialStock={{P,FHansaQuantity::FromRaw(20000)}};X.Inventories.Add(SI);FHansaInventoryInitialization MI;MI.Id=MId;MI.OwnerKind=EHansaInventoryOwnerKind::City;MI.CityId=R;MI.Capacity=FHansaQuantity::FromRaw(100000);MI.AcceptedGoods={B};X.Inventories.Add(MI);X.MarketSettings.UpdateCadenceTicks=5;X.MarketSettings.PriceHistoryCapacity=8;FHansaCityMarketInitialization MM;MM.CityId=R;MM.GoodId=B;MM.InventoryIds={MId};MM.DesiredReserve=FHansaQuantity::FromRaw(10000);MM.bMarketOnly=true;MM.MinimumPriceMilliMarks=100;MM.MaximumPriceMilliMarks=5000;MM.InitialPriceMilliMarks=1000;X.Markets.Add(MM);
 auto Made=FHansaSimulationState::TryCreate(MoveTemp(X));if(!TestTrue(TEXT("fixture"),Made.IsSuccess()))return false;FHansaSimulationState State=MoveTemp(Made.Value);FHansaSimulationTransientCache Cache;uint64 Q=1;auto Submit=[&](const auto& V){FHansaCommandHeader HD;HD.CommandId=FHansaCommandId::TryCreate(Q).Value;HD.GlobalSequence=Q++;HD.Authority={H,1,EHansaCommandOrigin::ControlledAutomation};HD.RequestedExecutionTick=State.CreateReadOnlyAccess(D).GetClock().GetTick();auto Cmd=FHansaGameplayCommand::Create(HD,V);return FHansaGameplayCommandGateway::ExecuteTick(State,D,MakeArrayView(&Cmd,1),Cache);};
 TestTrue(TEXT("privilege"),Submit(FHansaManageCityPrivilegeCommand{R,TEXT("AdditionalCommercialPlot"),IId,L2,EHansaCityPrivilegeAction::Acquire,0}).IsSuccess());TestTrue(TEXT("project"),Submit(FHansaFundCityProjectCommand{R,TEXT("PublicGranary"),IId,1}).IsSuccess());for(int N=0;N<3;++N)TestTrue(TEXT("tick"),FHansaGameplayCommandGateway::ExecuteTick(State,D,{},Cache).IsSuccess());auto Read=State.CreateReadOnlyAccess(D);TestEqual(TEXT("lease"),Read.GetLeasedPlots().Num(),2);TestEqual(TEXT("reserve"),Read.QueryMarket(R,B)->DesiredReserve.GetRawValue(),int64(30000));TestEqual(TEXT("money"),Read.GetHouses()[0].Money.GetRawValue(),int64(290000));TestEqual(TEXT("planks"),Read.GetInventories().QueryStock(IId,P)->Stock.GetRawValue(),int64(6000));const uint64 Hash=Read.GetFingerprint().Value;TestEqual(TEXT("Rostock governance gate"),Submit(FHansaTransitionCityAuthorityCommand{R,TEXT("Charter.Hamburg.FoundingCouncil"),3}).GetError(),EHansaCommandGatewayError::GovernanceScenarioGateRejected);TestEqual(TEXT("rollback"),State.CreateReadOnlyAccess(D).GetFingerprint().Value,Hash);TestTrue(TEXT("Hamburg charter transition"),Submit(FHansaTransitionCityAuthorityCommand{GCity,TEXT("Charter.Hamburg.FoundingCouncil"),0}).IsSuccess());const TOptional<FHansaForeignPresenceProjection> GovernanceProjection=State.CreateReadOnlyAccess(D).QueryForeignPresence(H,GCity);TestTrue(TEXT("governance projection"),GovernanceProjection.IsSet()&&GovernanceProjection.GetValue().bGovernanceAuthority&&GovernanceProjection.GetValue().GovernanceCharterId==TEXT("Charter.Hamburg.FoundingCouncil"));FHansaSaveSnapshot Save;Save.State=State;Save.BuildVersion=TEXT("TR-10");Save.SavedUtc=TEXT("2026-09-21T00:00:00Z");Save.Players={{1,H}};TArray<uint8> Bytes;TestTrue(TEXT("save"),FHansaSaveEnvelope::Encode(Save,D,Bytes).IsSuccess());FHansaSaveSnapshot Loaded;TestTrue(TEXT("load"),FHansaSaveEnvelope::Decode(Bytes,D,Loaded).IsSuccess());TestEqual(TEXT("hash"),Loaded.State.CreateReadOnlyAccess(D).GetFingerprint().Value,State.CreateReadOnlyAccess(D).GetFingerprint().Value);return !HasAnyErrors();
}
}

